---
- name: Powercycle the SUT
  hosts: localhost
  gather_facts: no
  vars:
    SUT: "{{ survey_SUT }}"
    BMC: "{{ survey_BMC }}"
    PDUIP1: "{{ survey_PDUIP1 }}"
    PDUIP2: "{{ survey_PDUIP2 }}"
    PDUPort1: "{{ survey_PDUPort1 }}"
    PDUPort2: "{{ survey_PDUPort2 }}"
    PDU_User: amd
    PDU_Password: AMDer123
  tasks:
    - name: Pinging SUT
      ansible.builtin.wait_for:
        host: "{{ SUT }}"
        state: started
        timeout: 5

    - name: Pinging BMC
      ansible.builtin.wait_for:
        host: "{{ BMC }}"
        state: started
        timeout: 5

    - name: Pinging PDU 1
      ansible.builtin.wait_for:
        host: "{{ PDUIP1 }}"
        state: started
        timeout: 5

    - name: Pinging PDU 2
      ansible.builtin.wait_for:
        host: "{{ PDUIP2 }}"
        state: started
        timeout: 5

    - name: Pinging PDUPort1
      ansible.builtin.wait_for:
        host: "{{ PDUPort1 }}"
        state: started
        timeout: 5

    - name: Pinging PDUPort2
      ansible.builtin.wait_for:
        host: "{{ PDUPort2 }}"
        state: started
        timeout: 5