---
- name: Powercycle the SUT
  hosts: localhost
  gather_facts: no
  vars:
    SUT: "{{ survery_SUT }}"
    BMC: "{{ survery_BMC }}"
    PDUIP1: "{{ survery_PDUIP1 }}"
    PDUIP2: "{{ survery_PDUIP2 }}"
    PDUPort1: "{{ survery_PDUPort1 }}"
    PDUPort2: "{{ survery_PDUPort2 }}"
    PDU_User: amd
    PDU_Password: AMDer123
  tasks:
    - name: Pinging SUT
      ansible.builtin.wait_for:
        host0: "{{ SUT }}"
        state: started
        timeout: 5
    - name: Pinging BMC
      ansible.builtin.wait_for:
        host1: "{{ BMC }}"
        state: started
        timeout: 5
    - name: Pinging PDU 1
      ansible.builtin.wait_for:
        host2: "{{ PDUIP1 }}"
        state: started
        timeout: 5
        host3: "{{ PDUIP2 }}"
        state: started
        timeout: 5
        host4: "{{ PDUPort1 }}"
        state: started
        timeout: 5
        host5: "{{ PDUPort2 }}"

        state: started
        timeout: 5
    #- name: Pinging PDU 2
    #- name:
    #- name:
    #- name:
    #- name:
    #- name:
    #- name:
