---
- name: Manage Background Task and Continue
  hosts: linux
  become: yes
  tasks:
    - name: Downloading stressng
      command: >
        wget -N ftp://10.230.136.14/Public/Rene/tests/sat.tar.xz -O /tmp/sat.tar.xz

    - name: Give chmod +x to tar.xz
      ansible.builtin.file:
        path: /tmp/sat.tar.xz
        mode: '0755'
        state: file

    - name: Extracting tar.xz
      ansible.builtin.unarchive:
        src: /tmp/sat.tar.xz
        dest: /tmp/
        remote_src: yes


    - name: Run Install Stream
      ansible.builtin.shell: /tmp/sat/install-sat-ubu.sh
      args:
        chdir: /tmp/sat/
        
    - name: Run Stream 86400
      ansible.builtin.shell: ./run-sat.sh 86400
      args:
        chdir: /tmp/sat/
      ignore_errors: yes
      environment:
        TERM: "xterm"

#    - name: Run install script asynchronously
#      ansible.builtin.command:
#        cmd: /tmp/sat/install-sat-ubu.sh
#      async: 86400  # Max run time in seconds (e.g., 24 hours)
#      poll: 10      # Check status every 10 seconds
#      register: async_result

#    - name: Wait for the install script to complete
#      ansible.builtin.async_status:
#        jid: "{{ async_result.ansible_job_id }}"
#      register: job_result
#      until: job_result.finished
#      retries: 8640  # Number of retries
#      delay: 10      # Delay between retries in seconds

#    - name: Run run-sat script
#      ansible.builtin.command:
#        cmd: /tmp/sat/run-sat.sh 86400 cmp
#      args:
#        chdir: /tmp/sat
#      when: job_result.finished

#    - name: Print job result
#      ansible.builtin.debug:
#        msg: "Install script completed with result: {{ job_result }}"
