---
- name: IP
  hosts: linux
  gather_facts: True
  become: yes
  #vars_files:
  #   - all.yml
  tasks:
    - name: Downloading kernel-compile
      command: >
        wget -N ftp://10.230.136.14/Public/Rene/tests/kernel-compile.tar.xz -O /tmp/kernel-compile.tar.xz
        
    - name: Gave chmod +x to tar.xz 
      ansible.builtin.file:
        path: /tmp/kernel-compile.tar.xz
        mode: '0755'
        state: file

    - name: Extracting tar.xz
      ansible.builtin.unarchive:
        src: /tmp/kernel-compile.tar.xz
        dest: /tmp/
        remote_src: yes

#---------------------------------------------------
#---------------------------------------------------
    - name: Run ins
      ansible.builtin.command:
        cmd: /tmp/kernel-compile/install-kernel-compile-ubu.sh
      args:
        chdir: /tmp/kernel-compile/
        
    - name: Run kernel-compile
      ansible.builtin.command:
        cmd: ./run-kernel-compile.sh 86400
        #cmd: /tmp/stressng/run-stressng.sh 86400 cmp
        
      args:
        chdir: /tmp/kernel-compile/
